#ifndef ROBOT_PROTOCOL_MOTION_LIFECYCLE_OPERATION_H
#define ROBOT_PROTOCOL_MOTION_LIFECYCLE_OPERATION_H

typedef enum
{
    MOTION_LIFECYCLE_OPERATION_NONE,
    MOTION_LIFECYCLE_OPERATION_ENSURE_STOPPED
} MotionLifecycleOperation;

#endif