#ifndef ROBOT_PROTOCOL_MOTION_LIFECYCLE_COMMAND_TYPE_H
#define ROBOT_PROTOCOL_MOTION_LIFECYCLE_COMMAND_TYPE_H

#include <stdint.h>

typedef uint8_t MotionLifecycleCommandType;

#define MOTION_LIFECYCLE_COMMAND_START_SESSION  0x01U
#define MOTION_LIFECYCLE_COMMAND_END_SESSION    0x02U

#endif
