#ifndef ROBOT_PROTOCOL_MOTION_LIFECYCLE_STATE_H
#define ROBOT_PROTOCOL_MOTION_LIFECYCLE_STATE_H

typedef enum
{
    MOTION_LIFECYCLE_STATE_NO_SESSION,
    MOTION_LIFECYCLE_STATE_STARTING,
    MOTION_LIFECYCLE_STATE_ACTIVE,
    MOTION_LIFECYCLE_STATE_ENDING
} MotionLifecycleState;

#endif