#ifndef ROBOT_PROTOCOL_PROTOCOL_FRAME_FORMAT_H
#define ROBOT_PROTOCOL_PROTOCOL_FRAME_FORMAT_H

#define PROTOCOL_FRAME_MAGIC_0 0xA5U
#define PROTOCOL_FRAME_MAGIC_1 0x5AU
#define PROTOCOL_FRAME_VERSION 0x01U

#define PROTOCOL_FRAME_HEADER_SIZE 8U
#define PROTOCOL_FRAME_CRC_SIZE 2U
#define PROTOCOL_FRAME_MAX_PAYLOAD_SIZE 64U

#define PROTOCOL_FRAME_MAX_WIRE_SIZE (PROTOCOL_FRAME_HEADER_SIZE + \
     PROTOCOL_FRAME_MAX_PAYLOAD_SIZE + \
     PROTOCOL_FRAME_CRC_SIZE)

#define PROTOCOL_FRAME_MAGIC_0_OFFSET          0U
#define PROTOCOL_FRAME_MAGIC_1_OFFSET          1U
#define PROTOCOL_FRAME_VERSION_OFFSET          2U
#define PROTOCOL_FRAME_MESSAGE_TYPE_OFFSET     3U
#define PROTOCOL_FRAME_SEQUENCE_OFFSET         4U
#define PROTOCOL_FRAME_PAYLOAD_LENGTH_OFFSET   6U
#define PROTOCOL_FRAME_PAYLOAD_OFFSET          8U

#endif