#ifndef ROBOT_PROTOCOL_PROTOCOL_INGRESS_ROUTER_H
#define ROBOT_PROTOCOL_PROTOCOL_INGRESS_ROUTER_H

#include "protocol_frame.h"

typedef enum
{
    PROTOCOL_INGRESS_ROUTE_INVALID_ARGUMENT,

    PROTOCOL_INGRESS_ROUTE_UNSUPPORTED_MESSAGE_TYPE,
    PROTOCOL_INGRESS_ROUTE_INVALID_PAYLOAD_LENGTH,

    PROTOCOL_INGRESS_ROUTE_LINK_SYNC,
    PROTOCOL_INGRESS_ROUTE_LINK_SYNC_OK,
    PROTOCOL_INGRESS_ROUTE_HEARTBEAT,

    PROTOCOL_INGRESS_ROUTE_MOTION_COMMAND,
    PROTOCOL_INGRESS_ROUTE_MOTION_ACK,
    PROTOCOL_INGRESS_ROUTE_MOTION_RESPONSE,

    PROTOCOL_INGRESS_ROUTE_WHEEL_VELOCITY
} ProtocolIngressRoute;

#ifdef __cplusplus
extern "C" {
#endif

ProtocolIngressRoute protocol_ingress_route(
    const ProtocolFrame* frame);

#ifdef __cplusplus
}
#endif

#endif